
# Dominica’s budgeting process {#appendixC} 

-	Every year, there is a budget calendar which is a list of sequence activities conducted by different stakeholders. A budget call is made, and a circular of guidelines to elaborate the budget proposal is sent to the MDAs.

-	After that, the MDAs have six weeks to elaborate the proposal. All MDAs submit estimates of recurrent and capital expenditure ; defend budgetary proposals during budget discussions and subsequent bilaterals.

-	The Ministry of Planning PSIP Unit reviews capital proposals with estimates; Undertake all tasks associated with the formulation and rationalization of the capital estimates prior to Cabinet approval; Submit capital estimates for Cabinet Approval; Prepare capital templates for Printery.

-	The Ministry of Finance reviews and rationalize recurrent proposals; Submit for the approval of Minister of Finance; Prepare and submit recurrent templates to Printery

-	The Ministry of Finance sends the budget for final approval to the House of Parliament.
